### ISSUE TITLE
Feature: Fade to black on load

### ISSUE THREAD

**Issue by SparkyRailgun** [mon/0x40-web#10]
Fade to black when the next song is triggered to load, to leave a black screen before the next track's map loads, rather than just leaving whatever was on screen last.

Really only mainly evident on larger tracks, but it feels like hues is frozen while the next track loads currently.

**Comment by mon** [comment]
Thoughts on "Loading..." in this black screen?

**Comment by SparkyRailgun** [comment]
Probably unnecessary, it should at most be on screen for a second, unless you do something like a Blade pack with a ton of 3 minute loops
