### ISSUE TITLE
Cannot read property 'blackout' of undefined

### ISSUE THREAD

**Issue by soruly** [mon/0x40-web#14]
Yesterday I was able to use 0x40 without problems, but got this error today.(refreshed with cache disabled)
![capture](https://cloud.githubusercontent.com/assets/1979746/15070695/7b872858-13b8-11e6-85c2-3495ff42230c.PNG)
Here is my localstorage
![1](https://cloud.githubusercontent.com/assets/1979746/15070750/e88fedae-13b8-11e6-8a82-db4496c91979.PNG)

I am using Chrome 50.0 on windows 7
It works fine in incognito mode

**Comment by mon** [comment]
Confirmed - I was calling an event handler too early.
