### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by db-kai** [mon/0x40-web#16]
I'm using inverted pictures so the background doesn't fk up based on your resolution.  The first character of my buildup is "i" so everything looks normal.  

I noticed the blackouts are white outs when inverted.  I think it'd be a good idea to include a white out character so things like this can be completely controlled.

**Comment by mon** [comment]
Use "¤"

It's a secret undocumented char for whiteout, but I think with Invert now a real feature it may need to become official.

**Comment by db-kai** [comment]
that...is brilliant.  :D
