### ISSUE TITLE
Permalink to the song playing

### ISSUE THREAD

**Issue by iamale** [mon/0x40-web#22]
Like http://0x40.mon.im/#song=madeon_-_finale or something like that (and just use that to override `firstSong`)?

**Comment by mon** [comment]
There is a very rough version of this at my custom URL which I use for loading respacks.
http://0x40.mon.im/custom.html?packs=drop_it.zip

I will incorporate it into the main release and let any variable be set via the URL. I will alias `firstSong` so you can just use `song` in the URL.

**Comment by mon** [comment]
Added in 378e415f18585f88fe08fd6f3ccb89941183f5b1, will be live soon. I think I'm due for a new official release within the next few weeks.
