### ISSUE TITLE
Multiple themes loaded at once

### ISSUE THREAD

**Issue by arknano** [mon/0x40-web#26]
Both modern and retro UIs are showing at once, with only modern set in the HTML settings.

**Comment by arknano** [comment]
Observed on http://0x40.sparkyrailgun.com/

Seems to happen on http://0x40.mon.im/ as well, but corrects itself after a short delay

**Comment by mon** [comment]
You've got the v3.1 javascript but an earlier css. Update to the latest css - it changes some `visibility` attributes to `inherit`, fixing this issue. It's related to 78116da737e556bc33b62d29eb5d4c8bf7909007
