### ISSUE TITLE
Blurring

### ISSUE THREAD

**Issue by benzrf** [mon/0x40-web#27]
As far as I can tell, you're currently faking the motion blurs by drawing a bunch of copies of the image. I just thought I'd mention that it's possible (albeit kind of hacky) to get genuine 1-dimensional gaussian blurring in canvas using SVG filters: [here's a demo](https://jsfiddle.net/0czfLepb/2/).

Sorry to waste your time if you already knew about this and had reasons not to do it this way!

**Comment by mon** [comment]
I did initially use an SVG blur, but it was _incredibly_ slow - on a full size image, I was getting under 15fps. Quasi blur is the best you'll get for realtime unless I move to WebGL ala [Kepstin's hues](https://github.com/kepstin/0x40hues-html5/)

**Comment by benzrf** [comment]
Ah, that's a shame :\

**Comment by benzrf** [comment]
Actually, how hard *would* it be to just transplant Kepstin's code?

**Comment by mon** [comment]
Annoyingly. Requires an entire rewrite of the rendering pipeline.
