### ISSUE TITLE
Undo is arbitrary and partly non-functional

### ISSUE THREAD

**Issue by SparkyRailgun** [mon/0x40-web#3]
Does not undo edits to the buildup

**Comment by SparkyRailgun** [comment]
Actually works in both, but i have no idea how it determines something worth undoing. It just ignored hundreds of inputs into the loop to undo another hundred things in the intro I hadn't touched since.

**Comment by mon** [comment]
After some more tests, undo does not work on atomic actions performed by the user and often fails to work properly. In addition, the undo buffer culling culls the wrong end of the buffer. Completely broken.
