### ISSUE TITLE
 How to run this file on your own server？

### ISSUE THREAD

**Issue by qylcx7758** [mon/0x40-web#31]
The step is too complicated，i just input this command 
 ```
 npm install gulp -g
  npm install
```
but error；

**Comment by qylcx7758** [comment]
In addtion,
`n = e("../build/libmpg123.js")`，
`  i.HTTPSource = e("./sources/node/http"),
            i.FileSource = e("./sources/node/file"),
            i.BufferSource = e("./sources/buffer"),
            i.Demuxer = e("./demuxer"),
            i.Decoder = e("./decoder"),
            i.AudioDevice = e("./device")`
Where are the files pointed to by these codes?

**Comment by qylcx7758** [comment]
In addtion,
```
n = e("../build/libmpg123.js")，
i.HTTPSource = e("./sources/node/http"), 
i.FileSource = e("./sources/node/file"),
 i.BufferSource = e("./sources/buffer"),
 i.Demuxer = e("./demuxer"),
 i.Decoder = e("./decoder"),
 i.AudioDevice = e("./device")
```
Where are the files pointed to by these codes?

**Comment by mon** [comment]
Just use the pre built zip from the releases page, it's easier.

**Comment by qylcx7758** [comment]
Yes, I can run successfully, thank you very much

**Comment by mon** [comment]
Great to hear! Thanks :)
