### ISSUE TITLE
Can this project decode AAC audio?

### ISSUE THREAD

**Issue by qylcx7758** [mon/0x40-web#32]
It only support MP3 and Ogg?

**Comment by mon** [comment]
Only if the browser supports aac natively - if it does  not, there is no fall-back

**Comment by qylcx7758** [comment]
This decoding module does not seem to support AAC, I use AAC audio, no error, but the song is not playing

**Comment by qylcx7758** [comment]
I use Google Chrome.

**Comment by qylcx7758** [comment]
In addition, I changed the method, using XMLHttpRequest to request AAC audio, and using this Worker to decode, but error.

**Comment by qylcx7758** [comment]
In addition, I changed the method, using XMLHttpRequest to request AAC audio, and using this Worker to decode, but error.
`A decoder for mp4a was not found`.

**Comment by mon** [comment]
Sounds like your browser doesn't support it, or you're accidentally piping it to the JS fallback (which _definitely_ doesn't support it). It's probably easier to just reencode to ogg here.

**Comment by qylcx7758** [comment]
I may describe unclear, this is a simple demo, you can see, it is used to decode your part.
If you request AAC audio, will be an error
https://github.com/qylcx7758/play-audio

**Comment by mon** [comment]
That's the "js fallback" I mentioned. It does not support aac, and I don't have plans to add support for it.

If you would like to add that support I'm afraid you'll need to do it yourself. Apologies.

**Comment by qylcx7758** [comment]
Well, I learned a lot about designing and decoding in this project.
Thanks.
