### ISSUE TITLE
Add direct link to the playing song (+settings?)

### ISSUE THREAD

**Issue by SirCmpwn** [mon/0x40-web#34]
Would be nice to link people to particular tracks. Great tool!

**Comment by mon** [comment]
In the editor you can enter something in the "link" box - clicking the song name in the UI should take you to the link. Is that what you're after?

**Comment by SirCmpwn** [comment]
No - I want to link people to *0x40* with something in the URL which specifies which track to play (out of the presets).

**Comment by mon** [comment]
Whilst not an obvious UI option...

You should be able to add the `song` param in the URL. It's a fuzzy search, so you can get away with a partial name.

eg: http://0x40.mon.im/?song=propane

**Comment by SirCmpwn** [comment]
Excellent, I'll definitely make use of that. It should be made more apparent that it's possible, though.

**Comment by mon** [comment]
I hope this is obvious enough in the Readme to close this issue
