### ISSUE TITLE
Whiteout effect while inverted has glitchy bright frame during fade

### ISSUE THREAD

**Issue by kepstin** [mon/0x40-web#37]
This is visible in the track "Alstroemeria Records - End of Daylight" on https://portal.0x40.ga/pack/17/view which makes heavy use of whiteouts while inverted to get a blackout effect.

**Comment by kepstin** [comment]
the only time I see this is when the blackout blur + blackout fade + invert are all in effect at the same time - then there's a flickering where some non-inverted frames are mixed in

the 0.25x speed mode is helpful for seeing that :)

**Comment by mon** [comment]
Fixed in 37c9d40780106e53b9bc0d4e3c4876166ce233e6 and released as v3.7
