### ISSUE TITLE
Animation sometimes isn't correct when using an animaition with beatsPerAnim and a song without charsPerBeat

### ISSUE THREAD

**Issue by kepstin** [mon/0x40-web#38]
To see this happen, open e.g. the "Illya Dance" respack from https://portal.0x40.ga/pack/22 along with any respack that contains songs without charsPerBeat.

If you set the image to "Miyu Edelfelt & Illyasviel von Einzbern" and then change the song from Popcorn Funk to another song, the animation will stop. Some actions (switching tabs/windows?) might restart it, but the speed will be inconsistent - extremely fast sometimes.

I'd expect the animation to switch to the speed defined by the frame durations.

**Comment by mon** [comment]
I believe this is fixed in v3.9, please re-open the issue if I missed any edge cases.
