### ISSUE TITLE
Volume cuts out per-song after a while

### ISSUE THREAD

**Issue by Atario** [mon/0x40-web#42]
Leave it running for some time, and eventually some songs have their volume cut way down.  Seems to go back to normal as the song is faded out, and the next song may or may not be normal.

(I'm on Firefox 75.0)

**Comment by mon** [comment]
So you've got autoplay turned on? Does the volume go down instantly or does it fade?

**Comment by Atario** [comment]
Yeah, I have AutoSong on "loop".  The volume for the song will start very low and stay there till it's time to fade out, at which point it snaps back to full, then immediately performs the fade-out.  Then the next song starts.
