### ISSUE TITLE
Error: Audio Worker cannot be started - correct path set in defaults?

### ISSUE THREAD

**Issue by Nawjy** [mon/0x40-web#43]
I apologize if this is a non issue not worth asking about, I am a brainlet.

I'm not trying to stick this on a server, I'm just trying to get an html folder I can locally.
I've made a respacks folder in the same directory as the html, I grabbed the respacks from your site and threw the default ones (charpackagev0.03.zip, defaults_v5.0.zip, huesmixA.zip) that the html points to into the respacks folder.

I haven't changed any of the [code](https://files.catbox.moe/ldzwtg.png) in the html file, the workersPath still points at "lib/workers/" and audio-worker.js is in the workers folder.
When running index.html I end up with the [error](https://files.catbox.moe/2u7xi6.png) in the subject, I assume I have the correct path because I haven't changed anything but as stated prior I don't know what I'm doing and am going off of my common sense, I've barely poked around with html before.

Thanks

**Comment by mon** [comment]
Running the html from a folder can be a bit janky due to cross origin security rules and subdirectories being a bit funky. You could try modifying the worker folder to be relative, ie `"./lib/workers/"` but it's been a while since I did that and it might not fix it.

If that doesn't fix it, it might be easiest to spin up a quick local web server to run it.

**Comment by Nawjy** [comment]
Well making it relative doesn't seem to change anything, so I suppose I'll look into the local web server thing. Time to dive into figuring that out, I appreciate the really quick reply. Thank you.

**Comment by mon** [comment]
If you have Python installed for whatever reason, running `python3 -m http.server` has been the easiest for me. Good luck :)

**Comment by Nawjy** [comment]
And it turns out since I had python installed already that it was really simple to figure out. Not as clean as just running the file when I want some colorized beat synchronized anime girls but this definitely works.
Thanks again!
