### ISSUE TITLE
cdn.0x40.ga is down

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [mon/0x40-web#53]
Domain referenced in source for getting respacks is down. Any clue where the packs it hosted went?

**Comment by TheAMM** [comment]
It's back at cdn.0x40hu.es. I'm not sure how the 0x40.ga domain expired (it's freenom free domain shit), but 0x40hu.es is the primary and can be changed back to.

**Comment by mon** [comment]
Fixed in a7b0f4c4c14cc90b48fdc978a6bb34ef63036edf, released as 3.8 and pushed to my host. Will be live when cloudflare decides to invalidate the cache.
