### ISSUE TITLE
0x40 Christmas edition is insufficiently comfy

### ISSUE THREAD

**Issue by ddevault** [mon/0x40-web#56]
**Expected behavior**

Comfy Christmas music plays while qt moeblobs appear in time with the music

**Actual behavior**

✓ Cute moeblobs
✗ Comfy music

**Comment by mon** [comment]
I guess the current songlist for Xmas is pretty boppy - I'd be happy to make a comfy variant, have you got any suggestions for tracks?

**Comment by ddevault** [comment]
Hm, I didn't realize there were several songs until I read your message and tried pressing a few keys at random to activate some hidden shortcuts. The other 0x40 deployments have a UI for switching between tracks. Maybe it should be updated?

I thought there was only one song, and it was not a very good one.

**Comment by mon** [comment]
I'm going to reopen this as a tracking issue to add the missing UI elements - I copied the Xmas flash which was simplified, but really there's no reason for it.

Additionally, of the additional tracks you're now aware of, got a favourite? Eve isn't the best, but it's a toss-up between the remainder. I can adjust the default track to suit..

**Comment by ddevault** [comment]
"Deck the Dubstep" is probably the most on-brand for 0x10 hues, I think.

**Comment by mon** [comment]
Xmas UI has been fixed (it matches Modern UI now) in b92d83a89ff132089013fa02e4d5da238606eedf, but I won't make a release for a bit, as I'm doing some experiments with effects and rendering stacks that might be worth bundling.
Can't get any info on the owner of the existing xmas hues so at the same time, I'll rehost with Deck the Dubstep as the default track.

Keeping both issues open til I make an actual release.

**Comment by ddevault** [comment]
Cool :)

**Comment by mon** [comment]
New render stacks didn't get finished, so I pushed the modularity work along with the Xmas UI fix as v4.2. Deck the Dubstep is now the default on my self-hosted xmas hues, so I'm closing this!

**Comment by ddevault** [comment]
Many thanks!
