### ISSUE TITLE
xmas.moe is missing an https redirect

### ISSUE THREAD

**Issue by ddevault** [mon/0x40-web#57]
While you're working on it anyway, port 80 should redirect to 443.

**Comment by mon** [comment]
I don't actually know who hosts that particular domain - it's a few versions behind (mostly just loading speed improvements and extra effects that the xmas charts don't use). I've started a call to find who hosts it, if I can't find out I'll just host my own up-to-date xmas hues.

**Comment by ddevault** [comment]
Cheers!

**Comment by mon** [comment]
Have found and contacted the owner (twitter: azuretan). Until they've sorted it, I am now hosting xmas hues and have redirected the README link.

xmas.moe is a much better domain name, so once it's fixed I will change the link back.

**Comment by mon** [comment]
xmas.moe has expired, so I bought it for the next 3 years (and will keep renewing it as long as I remain alive, I think...).

https won't be active for up to 48 hours as cloudflare works itself out, but http is being served. I'll update the README and close this ticket when it's all sorted.

**Comment by mon** [comment]
Looks all good - readme changed (and fixed a few other readme nits while I was at it).
