### ISSUE TITLE
Local python hosting of hues has HTTP 204 no content for respacks

### ISSUE THREAD

**Issue by mon** [mon/0x40-web#80]
Seems related to external download manager software seeing a .zip and getting overly excited?

also i try run py3 same error -_-
![image](https://user-images.githubusercontent.com/38723240/232510079-f33e1be7-1f7a-454e-8e29-3b018a1864d1.png)

_Originally posted by @thisfardi in https://github.com/mon/0x40-web/issues/47#issuecomment-1511430180_
_Moving to its own issue due to spamming of an unrelated issue._

**Comment by mon** [comment]
That log looks nothing like a hues request page - there's no request for any .js files, nor any of the .png files.

I am still wondering what the external download manager in use is - please disable it and try again, to eliminate this as a source of the issue.

**Comment by thisfardi** [comment]
> Seems related to external download manager software seeing a .zip and getting overly excited?
> 
> also i try run py3 same error -_- ![image](https://user-images.githubusercontent.com/38723240/232510079-f33e1be7-1f7a-454e-8e29-3b018a1864d1.png)
> 
> _Originally posted by @thisfardi in [#47 (comment)](https://github.com/mon/0x40-web/issues/47#issuecomment-1511430180)_ _Moving to its own issue due to spamming of an unrelated issue._


thanks for new issue bro _ / \ _ 

can u update this asset include respacks bro 
![image](https://user-images.githubusercontent.com/38723240/232512772-a794e700-dbfe-446f-bb45-27308004706d.png)

**Comment by thisfardi** [comment]
> And ideally tell me what download manager it is, as well

ok bro ill try

**Comment by mon** [comment]
"Download complete"
WHAT IS THIS APP

**Comment by thisfardi** [comment]
> "Download complete" WHAT IS THIS APP

thats hue & respaks
![image](https://user-images.githubusercontent.com/38723240/232516239-08c18a51-d73d-455a-9048-4301e8bbb10e.png)

**Comment by mon** [comment]
Google chrome does NOT look like this. You have a 3rd party app installed. What is the app called?
![image](https://user-images.githubusercontent.com/3398021/232516498-e351413d-1bfc-4299-aa87-2d68c0562ac1.png)

**Comment by thisfardi** [comment]
i try on 2 browser in chrome & firefox still same issue

if view on network log his GET source from folder respacks bro and download it

**Comment by mon** [comment]
This program in the screenshot is Internet Download Manager.

"I non actived" - this is clearly false, because it appears in the screenshot. Disable it properly.

**Comment by mon** [comment]
Did you read the README properly? Where are your respacks when running webpack?

**Comment by mon** [comment]
....Old mate deleted all his comments. What a pain.
