### ISSUE TITLE
Remote respacks not loading

### ISSUE THREAD

**Issue by defaultxr** [mon/0x40-web#81]
Seems to be a similar issue to #53 - cdn.0x40hu.es does not respond (nor even to ping), so when attempting to load the remote respacks, it eventually times out and says "Could not load list! Click to try again". Is it possible to get a fix, or if not, are the respacks still available somewhere else?

**Comment by TheAMM** [comment]
Will be back sometime later, the cheapo provider turned into dust and I haven't had the energy to setup a new server.

**Comment by mon** [comment]
This has been fixed for a while, forgot to close the issue~
